In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [3]:

X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1

(2, 3)
(2,)
(3,)


In [4]:

Z1 = sigmoid(A1)

print(A1)
print(Z1)


[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [5]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

(3,)
(3, 2)
(2,)


In [6]:
def identify_function(x):
    return X
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = identify_function(A3)

In [7]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2,0.4,0.6]])
    network['b1'] = np.array([0.1,0.2,0.3])
    network['W2'] = np.array([[0.1,0.4], [0.2,0.5], [0.3,0.6]])
    network['b2'] = np.array([0.1,0.2])
    network['W3'] = np.array([[0.1,0.3], [0.2,0.4]])
    network['b3'] = np.array([0.1,0.2])
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3) + b3
    y = identify_function(a3)
    
    return y

network = init_network()
x = np.array([0.1,0.5])
y = forward(network, x)
print(y)

[1.  0.5]


In [8]:
#softmax function(소프트맥스 함수) 구현
a = np.array([0.3, 2.9, 4.0])       #숫자 배열 선언
exp_a = np.exp(a)                   #지수함수에 대입
print(exp_a)                        #대입한 값 출력

sum_exp_a = np.sum(exp_a)           #각 배열값 대입한 값들의 합
print(sum_exp_a)

y = exp_a / sum_exp_a               #각 배열 값을 분자로, 각 배열값 대입한 값들의 합을 분모로
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [9]:
def softmax(a):                 #softmax 함수 선언
    exp_a = np.exp(a)           #배열값 지수함수에 대입
    sum_exp_a = np.sum(exp_a)   #지수함수에 대입한 값들의 합
    y = exp_a / sum_exp_a       #분자는 지수함수에 대입한 값, 분모는 지수함수에 대입한 값들의 합
    
    return Y                    #계산값을 반환

In [10]:
'''
softmax function의 문제점
지수함수 특성상 결과값들이 기하급수적으로 커짐
'''

'\nsoftmax function의 문제점\n지수함수 특성상 결과값들이 기하급수적으로 커짐\n'

In [11]:
a = np.array([1010,1000,990])
np.exp(a) / np.sum(np.exp(a))   #소프트맥스 함수의 문제점(오버플로)

C:\Users\mingk\AppData\Local\Temp\ipykernel_6732\4168977782.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))   #소프트맥스 함수의 문제점(오버플로)
C:\Users\mingk\AppData\Local\Temp\ipykernel_6732\4168977782.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))   #소프트맥스 함수의 문제점(오버플로)


array([nan, nan, nan])

In [12]:
c = np.max(a)
print(a - c)
np.exp(a-c)/np.sum(np.exp(a-c))

[  0 -10 -20]


array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [13]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

In [14]:
a = np.array([0.3, 2.9,4.0])
y = softmax(a)
print(y)
np.sum(y)
print(np.sum(y))

[0.01821127 0.24519181 0.73659691]
1.0


In [15]:
import sys, os
sys.path.append(os.pardir)
#from dataset.mnist import load_mnist

from ok.mnist_pra import load_mnist

(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

print(x_train.shape)
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

ModuleNotFoundError: No module named 'ok.mnist_pra'

In [ ]:
import sys, os
sys.path.append(os.pardir)
from ok.mnist_pra import load_mnist
from PIL import Image

def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))
    pil_img.show()

(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

img = x_train[0]
label = t_train[0]
print(label)

print(img.shape)
img = img.reshape(28,28)
print(img.shape)

img_show(img)

5
(784,)
(28, 28)


In [ ]:
import pickle       # 왜 책에는 없는거지..

# Save pickle
#with open("sample_weight.pk1","wb") as fw:
 #   pickle.dump(dataset.mnist   , fw)

In [ ]:
def get_data():
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(normalize = True, flatten=True, one_hot_label = False)
    return x_test, t_test

def init_network():
    with open("sample_weight.pkl", 'rb') as f:
        network = pickle.load(f)
    return network

def predict(network, x):
    W1,W2,W3 = network['W1'], network['W2'], network['W3']
    b1,b2,b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    y = softmax(a3)
    
    return y

In [ ]:
x, t = get_data()
network = init_network()

accuracy_cnt = 0
for i in range(len(x)):
    y = predict(network, x[i])
    p = np.argmax(y)
    if p == t[i]:
        accuracy_cnt += 1
        
print("Accuracy:" + str(float(accuracy_cnt)/len(x)))

Accuracy:0.9352


In [ ]:
x, _ = get_data()
network = init_network()
W1, W2, W3 = network['W1'], network['W2'], network['W3']

print(x.shape)
x[0].shape
print(W1.shape)
print(W2.shape)
print(W3.shape)

(10000, 784)
(784, 50)
(50, 100)
(100, 10)


In [ ]:
x, t = get_data()
network = init_network()

batch_size = 100
accuracy_cnt = 0

for i in range(0, len(x), batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = predict(network, x_batch)
    p = np.argmax(y_batch, axis = 1)
    accuracy_cnt += np.sum(p == t[i:i+batch_size])