In [1]:
# @ A = XW + B 구현하기 (3층)  
import numpy as np
X = np.array([1.0, 5.0])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X,W1) + B1                 #np.dot이 뭐였지? => 행렬 내적 Q. ()의 순서가 중요한가?
print(A1)                              #!!!!!중요했음 덜덜티비 두 행렬의 차원의 원소수를 고려하자
#A1 = np.dot(W1,X) + B1     
#print(A1)

(2, 3)
(2,)
(3,)
[1.2 2.5 3.8]


In [11]:
# @에 활성화 함수(sigmoid) 넣기
import numpy as np
def sigmoid(x):                                        
    return 1/(1+np.exp(-x))                            #exp도 넘파이 출신이었..

X = np.array([1.0, 5.0])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X,W1) + B1

Z1 = sigmoid(A1)

print(A1)
print(Z1)

[1.2 2.5 3.8]
[0.76852478 0.92414182 0.97811873]


In [16]:
#1층에서 2층으로 신호 전달
def sigmoid(x):
    return 1/(1+np.exp(-x))

X = np.array([1.0, 5.0])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X,W1) + B1                                   #여기까지는 1층
Z1 = sigmoid(A1)

W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])        #여기서부터 2층
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1,W2)+B2
Z2 = sigmoid(A2)
print(A2)

(3,)
(3, 2)
(2,)
[0.65511646 1.55635206]


In [25]:
#2층에서 3층으로 신호 전달
def identify_function(x):
    return x

def sigmoid(x):
    return 1/(1+np.exp(-x))

X = np.array([1.0, 5.0])
W1 = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

A1 = np.dot(X,W1) + B1                                   #여기까지는 1층
Z1 = sigmoid(A1)

W2 = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])        #여기서부터 2층
B2 = np.array([0.1, 0.2])

A2 = np.dot(Z1,W2)+B2
Z2 = sigmoid(A2)
print(Z2)

W3 = np.array([[0.1, 0.3],[0.2, 0.4]])                  #여기서부터 3층
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2,W3)+B3                                        #바꿔도 상관없나? A3 = np.dot(W3,Z2)+B3 => 값은 나오는데 다름 ??? 다른건가?
print(A3)
#A3 = np.dot(W3,Z2)+B3
#print(A3) 

Y=identify_function(A3)
print(Y)

[0.65816252 0.82582927]
[0.33098211 0.72778046]
[0.33098211 0.72778046]


회귀 : 항등함수를<br>
2클래스 분류 : 시그모이드함수<br>
다중 클래스 분류 : 소프트맥스 함수<br>

회귀란 광어는 3kg다
분류는 고양이vs강아지 분류

In [23]:
#3층퍼셉트론 구현 총정리
def identify_function(x):
    return x

def sigmoid(x):
    return 1/(1+np.exp(-x))

def init_network():                                                   #왜 init으로 하지? => initialize 초기화  
    network = {}                                                      #딕셔너리 만들기
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])      #파이썬의 딕셔너리 키에따른 값을 넣어준다. 
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5],[0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    
    return network                                                   #여러개를 반환하기 위해서 딕셔너리 사용

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']        #간단하게 사용하기 위해 각 딕셔너리를 w1,w2,w3로 넣어준다
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2,W3) + b3
    y = identify_function(a3)
    
    return y

network = init_network()                                    
x = np.array([1.0, 0.5])
y = forward(network, x)                                      #함수안에 함수가 들어갈 수 있나? 윗줄에서 딕셔너리를 반환하였으므로 딕셔너리가 들어간 것임.
print(y)

[0.31682708 0.69627909]


***3.5 출력층 설계하기***<br>
회귀에는 왜 항등함수를?<br>
0~1값이 필요한것이 아니기때문에<br>
분류에는 왜 소프트맥스함수를?<br>
확률을 사용하기 때문에

In [33]:
#소프트맥스 함수 구현-0 (기초)
a = np.array([0.3, 2.9, 4.0])

exp_a = np.exp(a)
print(exp_a)

sum_exp_a = np.sum(exp_a)                              #sum도 있구나 자동으로 배열을 만들어서 더해주네
print(sum_exp_a)

y = exp_a / sum_exp_a
print(y)

[ 1.34985881 18.17414537 54.59815003]
74.1221542101633
[0.01821127 0.24519181 0.73659691]


In [34]:
#소프트맥스 함수 구현-1  (문제발생)
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    
    return y

문제점 지수함수는 너무 쉽게 큰값을 내뱉는다. *오버플로 발생!!!*

In [39]:
#소프트맥스 함수 구현-2   (해결-1)
a = np.array([1010, 100, 990])
np.exp(a) / np.sum(np.exp(a))                #오버플로 발생***!!!!

c = np.max(a)
print(a - c)

print(np.exp(a-c) / np.sum(np.exp(a-c)))

[   0 -910  -20]
[9.99999998e-01 0.00000000e+00 2.06115362e-09]


C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_129232\1369726986.py:3: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))                #오버플로 발생***!!!!
C:\Users\SAMSUNG\AppData\Local\Temp\ipykernel_129232\1369726986.py:3: RuntimeWarning: invalid value encountered in true_divide
  np.exp(a) / np.sum(np.exp(a))                #오버플로 발생***!!!!


In [29]:
#소프트맥스 함수 구현 최종
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a-c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a/sum_exp_a
    
    return y
    
    

In [30]:
#소프트맥스 함수의 특징
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print(y)
np.sum(y)

[0.01821127 0.24519181 0.73659691]


1.0

소프트맥스 함수는 출력값의 총합이 1이다!
함수의 출력은 0~1.0 사이의 실수이다.
***굉장히 중요한 성질***

소프트맥스 함수를 거치기 전과 후 그 수들의 대소관계는 변하지 않음. 따라서 출력층에 활성화함수안써도 오키도퀴

In [2]:
#3.6 손글씨 숫자 인식 (MNIST data이용)
import sys, os                           #경로관리
sys.path.append(os.pardir)               #책: 부모 디렉터리의 파일을 가져올 수 있도록 설정
from dataset.mnist import load_mnist     #부모디렉토리 파일을 가져올 수 있도록 dataset에서 load_ 가져옴

#책: 처음 한 번은 몇 분 정도 걸립니다. : 완~~전 오래걸림 
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)         #flatten : 평탄하게 (1차원배열로) normalize 0~1까지로 one_hot_lable 맞는거만 1로 나머지 0
                                                                      #mnist함수를 이용하여 가져옴
#책: 각 데이터의 형상 출력
print(x_train.shape)       
print(t_train.shape)
print(x_test.shape)
print(t_test.shape)

(60000, 784)
(60000,)
(10000, 784)
(10000,)


In [5]:
#이미지 보기
import sys, os
sys.path.append(os.pardir)                  
import numpy as np
from dataset.mnist import load_mnist
from PIL import Image                                      #이미지 보여줄 수 있도록

def img_show(img):
    pil_img = Image.fromarray(np.uint8(img))               #이미지 보여주는 명령어(어레이를 이미지로)
    pil_img.show()
    
(x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)

img = x_train[0]                                           #첫번째 이미지
label = t_train[0]                                         
print(label) 

print(img.shape)
img = img.reshape(28,28)                                   #크기 복원
print(img.shape)

img_show(img)

5
(784,)
(28, 28)


In [26]:
#신경망의 추론처리 위의 코드 신경망으로 구현하기
import pickle

def get_data():                                                               #mnist 받기
    (x_train, t_train), (x_test, t_test) = \
        load_mnist(normalize = True, flatten = True, one_hot_label =False)    #\다음줄이랑 연결한다는 뜻으로 그 사이에는 주석을 못쓴다
    return x_test, t_test                                                                                                

def init_network():                                                           #파일 가져오기: 딕셔너리 변수로 저장된 학습된 가중치 매개변수 
    with open("sample_weight.pkl", 'rb') as f:                                #파일 열기
        network = pickle.load(f)
        
    return network

def predict(network, x):                                                     #추론하기 
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']
    
    a1 = np.dot(x,W1)+b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1,W2)+b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, W3)+b3
    y = softmax(a3)
    
    return y

In [33]:
#추론의 정확도 알아보기
x, t = get_data()                                           #파일 데이터 받기
network = init_network()                                    #네트워크로 가중치 받기

accuracy_cnt = 0 
for i in range(len(x)):                                     #for문으로 한장씩 꺼냄
    y = predict(network, x[i])                              #predict()로 분류
    p = np.argmax(y)                                        #책: 확률이 가장 높은 원소의 인덱스를 얻는다.
    if p == t[i]:                                           #예측한것이 맞으면
        accuracy_cnt += 1                                   # +1
        
print("Accuracy:" +str(float(accuracy_cnt) / len(x)))      #예측한 정답 갯수 / 전체 정답 레이블 => 정확도 구하기

Accuracy:0.9352


normalize = True
정규화로 전처리과정을 거침.
이 장에서는 255로 나누는 간단한 전처리를 했지만 현업에서는 다양한 전처리과정이 있음

In [49]:
#3.6.3 배치 처리
x, _ = get_data()
network = init_network()
W1, W2, W3 = network['W1'], network['W2'], network['W3']

print(x.shape)
print(x[0].shape)
print(W1.shape)
print(W2.shape)
print(W3.shape)

(10000, 784)
(784,)
(784, 50)
(50, 100)
(100, 10)


In [41]:
#배치 처리 구현
x, t = get_data()
network = init_network()

batch_size = 100                                                 #100짜리 배치 
accuracy_cnt = 0

for i in range(0, len(x), batch_size):                           #총만장을 백장씩 끊어서 한다
    x_batch = x[i:i+batch_size]                                  #i번째부터 i+배치사이즈 만큼 가져옴
    y_batch = predict(network, x_batch)                          #예측하는거
    p = np.argmax(y_batch, axis=1)                               #제일 큰 값 : axis = 1 1차원 axis = 0 0차원   
    accuracy_cnt += np.sum(p == t[i:i+batch_size])               #0또는 1값을 가진 데이터들의 합을 cnt에 더해준다.
    
print("Accuracy:" + str(float(accuracy_cnt) /len(x)))

Accuracy:0.9352


In [45]:
#리스트 부가 설명
print(list(range(0,10)))                             #2개 작성하면 어디부터 어디 전까지
print(list(range(0,10,3)))                           #3개 작성하면 어디부터 어디 전까지 몇차이씩

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 3, 6, 9]


In [46]:
#argmax 부가 설명
x = np.array([[0.1, 0.8, 0.1],[0.3, 0.1, 0.6],[0.2, 0.5, 0.3],[0.8, 0.1, 0.1]])
y = np.argmax(x, axis=1)                                #axis = 1에 주의하자 1번째 차원을 축으로 axis = 0은 0번째 차원이 가장 처음의 차원 
print(y) 

[1 2 1 0]


In [48]:
y = np.array([1,2,1,0])
t = np.array([1,2,0,0])
print(y==t)                              #bool형을 반환
print(np.sum(y==t))                      #참이 3개이므로 1+1+1은 3

[ True  True False  True]
3
